### ISSUE TITLE
Problem when starting QIdle

### ISSUE THREAD

**Issue by atuor** [ColinDuquesnoy/QIdle#1]
Hi Colin

When I try to start QIdle I get the Traceback below. Could you please help me out here?
I'm running an Ubuntu 14.04.

$ QIdle
2015-07-20 00:21:03::INFO::root::Test
2015-07-20 00:21:03::INFO::qidle.app::QIdle v0.2.0
2015-07-20 00:21:03::INFO::qidle.app::libraries.zip is up to date
2015-07-20 00:21:03::INFO::qidle.app::reopen last window: None
Traceback (most recent call last):
  File "/usr/local/bin/QIdle", line 9, in <module>
    load_entry_point('QIdle==0.2.0', 'gui_scripts', 'QIdle')()
  File "/usr/local/lib/python2.7/dist-packages/qidle/main.py", line 12, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/qidle/app.py", line 236, in run
    self.init()
  File "/usr/local/lib/python2.7/dist-packages/qidle/app.py", line 224, in init
    if os.path.isfile(path):
  File "/usr/lib/python2.7/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by ColinDuquesnoy** [comment]
Hi @atuor 

QIdle is meant to be run by a **python3** interpreter. 

1) Use **pip3** to install QIdle and its dependencies
2) Start the installed QIdle binary from the terminal, it should use the python3 interpreter

Note that while the IDE run with python3, it can target another python interpreter to run you scripts.

FYI, QIdle is going to disappear soon, it will be replace by another project of mine: https://github.com/HackEdit/hackedit. HackEdit is already much more complete than QIdle (there are already some refactoring and debugging capabilities) but you'll have to wait a month or two before the first official alpha release is published.

**Comment by ColinDuquesnoy** [comment]
Please also note that I just fixed a startup error when used with python3, so make sure to use the latest commit from today...

**Comment by atuor** [comment]
Hi @ColinDuquesnoy 

Thanks a lot! Am looking forward to try HackEdit :+1:
